# Generated by Django 6.0.6 on 2026-06-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la parroquia')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del barrio')),
                ('num_viviendas', models.IntegerField(verbose_name='Número de viviendas')),
                ('num_parques', models.IntegerField(verbose_name='Número de parques')),
                ('num_edificios_residenciales', models.IntegerField(verbose_name='Número de edificios residenciales')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_barrios', to='ordenamiento.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='PresidenteBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30, unique=True, verbose_name='Cédula de identidad')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_presidentes', to='ordenamiento.barrio')),
            ],
        ),
    ]
